
export const interviewCovers = [
    "/adobe.png",
    "/amazon.png",
    "/facebook.png",
    "/hostinger.png",
    "/pinterest.png",
    "/quora.png",
    "/reddit.png",
    "/skype.png",
    "/spotify.png",
    "/telegram.png",
    "/tiktok.png",
    "/yahoo.png",
  ];

  export const dummyInterviews=[
    {
      "id": "1",
      "userId": "user1",
      "role": "Frontend Developer",
      "type": "Technical",
      "techstack": ["React", "TypeScript", "Next.js", "Tailwind CSS"],
      "level": "Junior",
      "questions": ["What is React?"],
      "finalized": false,
      "createdAt": "2024-03-15T10:00:00Z"
    },
    {
      "id": "2",
      "userId": "user2",
      "role": "Backend Developer",
      "type": "Technical",
      "techstack": ["Node.js", "Express", "MongoDB", "Docker"],
      "level": "Mid-Level",
      "questions": ["What is Node.js?"],
      "finalized": true,
      "createdAt": "2024-04-10T12:30:00Z"
    },
    {
      "id": "3",
      "userId": "user3",
      "role": "Full Stack Developer",
      "type": "Technical",
      "techstack": ["React", "Node.js", "GraphQL", "PostgreSQL"],
      "level": "Senior",
      "questions": ["Explain GraphQL advantages."],
      "finalized": false,
      "createdAt": "2024-05-20T14:15:00Z"
    },
    {
      "id": "4",
      "userId": "user4",
      "role": "UI/UX Designer",
      "type": "Design",
      "techstack": ["Figma", "Adobe XD", "CSS", "JavaScript"],
      "level": "Junior",
      "questions": ["What are UX principles?"],
      "finalized": false,
      "createdAt": "2024-06-05T09:45:00Z"
    },
    {
      "id": "5",
      "userId": "user5",
      "role": "DevOps Engineer",
      "type": "Technical",
      "techstack": ["AWS", "Kubernetes", "Terraform", "CI/CD"],
      "level": "Mid-Level",
      "questions": ["Explain CI/CD pipelines."],
      "finalized": true,
      "createdAt": "2024-07-12T16:20:00Z"
    }
  ]
  export const mappings = {
    "react.js": "react",
    reactjs: "react",
    react: "react",
    "next.js": "nextjs",
    nextjs: "nextjs",
    next: "nextjs",
    "vue.js": "vuejs",
    vuejs: "vuejs",
    vue: "vuejs",
    "express.js": "express",
    expressjs: "express",
    express: "express",
    "node.js": "nodejs",
    nodejs: "nodejs",
    node: "nodejs",
    mongodb: "mongodb",
    mongo: "mongodb",
    mongoose: "mongoose",
    mysql: "mysql",
    postgresql: "postgresql",
    sqlite: "sqlite",
    firebase: "firebase",
    docker: "docker",
    kubernetes: "kubernetes",
    aws: "aws",
    azure: "azure",
    gcp: "gcp",
    digitalocean: "digitalocean",
    heroku: "heroku",
    photoshop: "photoshop",
    "adobe photoshop": "photoshop",
    html5: "html5",
    html: "html5",
    css3: "css3",
    css: "css3",
    sass: "sass",
    scss: "sass",
    less: "less",
    tailwindcss: "tailwindcss",
    tailwind: "tailwindcss",
    bootstrap: "bootstrap",
    jquery: "jquery",
    typescript: "typescript",
    ts: "typescript",
    javascript: "javascript",
    js: "javascript",
    "angular.js": "angular",
    angularjs: "angular",
    angular: "angular",
    "ember.js": "ember",
    emberjs: "ember",
    ember: "ember",
    "backbone.js": "backbone",
    backbonejs: "backbone",
    backbone: "backbone",
    nestjs: "nestjs",
    graphql: "graphql",
    "graph ql": "graphql",
    apollo: "apollo",
    webpack: "webpack",
    babel: "babel",
    "rollup.js": "rollup",
    rollupjs: "rollup",
    rollup: "rollup",
    "parcel.js": "parcel",
    parceljs: "parcel",
    npm: "npm",
    yarn: "yarn",
    git: "git",
    github: "github",
    gitlab: "gitlab",
    bitbucket: "bitbucket",
    figma: "figma",
    prisma: "prisma",
    redux: "redux",
    flux: "flux",
    redis: "redis",
    selenium: "selenium",
    cypress: "cypress",
    jest: "jest",
    mocha: "mocha",
    chai: "chai",
    karma: "karma",
    vuex: "vuex",
    "nuxt.js": "nuxt",
    nuxtjs: "nuxt",
    nuxt: "nuxt",
    strapi: "strapi",
    wordpress: "wordpress",
    contentful: "contentful",
    netlify: "netlify",
    vercel: "vercel",
    "aws amplify": "amplify",
  };
    